config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  root :to => 'welcome#index'
  get 'welcome/index'
  get 'aulas/index'
  get 'aulas/new'
  resources :aulas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aula.rb
class Aula < ApplicationRecord
end

app/models/curso.rb
class Curso < ApplicationRecord

CLASS_LIST_TURNO= ["Mañana", "Tarde", "Noche"]
CLASS_LIST_COMISION=["1A","1B","1K","2A","2B","3A","3B","3K","4A","4B","4K"]
CLASS_LIST_CARRERA=["Lic. en Informática","Ing. en Sistemas"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index
        @tutor='El grupo de Ruby On Rails'
    
        @cursoscargados=Curso.count
        @aulascargadas=Aula.count
    
        @aulastodas=Aula.all
        @cursostodos=Curso.all
    
    
       
    
    @cursosmañana=Curso.where(turno:'Mañana')
    @cursostarde=Curso.where(turno:'Tarde')
    @cursosnoche=Curso.where(turno:'Noche')
    
    @dias=["Lunes","Martes","Miecoles","Jueves","Viernes"]
    
      end

      
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: [:show, :edit, :update, :destroy]

  # GET /aulas
  # GET /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1
  # GET /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

  # POST /aulas
  # POST /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: 'Aula was successfully created.' }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1
  # PATCH/PUT /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: 'Aula was successfully updated.' }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1
  # DELETE /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: 'Aula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aula_params
      params.require(:aula).permit(:numero, :piso, :capacidad, :asignada)
    end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nombre, :carrera, :cantidadalumnos, :turno, :comision, :asignado)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tutor='El grupo de Ruby On Rails'

    @cursoscargados=Curso.count
    @aulascargadas=Aula.count

    @aulastodas=Aula.all
    @cursostodos=Curso.all


   

@cursosmañana=Curso.where(turno:'Mañana')
@cursostarde=Curso.where(turno:'Tarde')
@cursosnoche=Curso.where(turno:'Noche')

@dias=["Lunes","Martes","Miecoles","Jueves","Viernes"]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aulas/_form.html.erb
<head>
    <title>Nuevo Curso</title>
      <nav class="be-red white">
    <ul class = "no-list row center-xs">
      <li class ="col-md">
      <%= link_to 'Agregar Curso', new_curso_path %>
     </li>
     <li class ="col-md">
      <%= link_to 'lista de cursos', cursos_path %>
     </li>
    </ul>
  </nav>
</head>
<body>
  <%= form_with(model: aula, local: true) do |form| %>
    <% if aula.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(aula.errors.count, "error") %> prohibited this aula from being saved:</h2>
        <ul>
        <% aula.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div id="wrapper">
     <form action="" method="post">
       <fieldset>
        <legend>NUEVO AULA</legend>
        <div class="field">
          <%= form.label :numero %>
          <%= form.number_field :numero %>
        </div>

        <div class="field">
          <%= form.label :piso %>
          <%= form.number_field :piso %>
        </div>

        <div class="field">
          <%= form.label :capacidad %>
          <%= form.number_field :capacidad %>
        </div>

        <div class="field">
          <%= form.label :asignada %>
          <%= form.check_box :asignada %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
        <% end %>
      </fieldset>    
    </form>
  </div>
</body>

app/views/aulas/edit.html.erb
<h1>Editing Aula</h1>

<%= render 'form', aula: @aula %>

<div class="btn">
    <%= link_to 'Ver', @aula %> |
    <%= link_to 'Volver', aulas_path %>
</div>

app/views/aulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Aulas</h1>
<h2>Tutor: <%= @tutor %></h2>

<header>
  <nav class="be-red white">
    <ul class = "no-list row center-xs">
     <li class ="col-md">
      <%= link_to 'Agregar Curso', new_curso_path %>
     </li>
      <li class ="col-md">
      <%= link_to 'Agregar Aula', new_aula_path %>
     </li>
    </ul>
  </nav>
</header>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Piso</th>
      <th>Capacidad</th>
      <th>Asignada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aulas.each do |aula| %>
      <tr>
        <td><%= aula.numero %></td>
        <td><%= aula.piso %></td>
        <td><%= aula.capacidad %></td>
        <td><%= aula.asignada %></td>
        <td><%= link_to 'Show', aula %></td>
        <td><%= link_to 'Edit', edit_aula_path(aula) %></td>
        <td><%= link_to 'Destroy', aula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/aulas/new.html.erb
<h1>Nuevo Aula</h1>

<%= render 'form', aula: @aula %>
<!--iv class="btn">
<%= link_to 'Volver', aulas_path %>
</div> -->

app/views/aulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @aula.numero %>
</p>

<p>
  <strong>Piso:</strong>
  <%= @aula.piso %>
</p>

<p>
  <strong>Capacidad:</strong>
  <%= @aula.capacidad %>
</p>

<p>
  <strong>Asignada:</strong>
  <%= @aula.asignada %>
</p>

<div class="btn">
<%= link_to 'Edit', edit_aula_path(@aula) %> |
<%= link_to 'Back', aulas_path %>
</div>

app/views/cursos/_form.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd"
    >
<html lang="en">
<head>
    <title>Nuevo Curso</title>  
</head>

<header>
  <nav class="be-red white">
    <ul class = "no-list row center-xs">
     <li class ="col-md">
      <a href="/cursos">Lista de cursos</a>
     </li>
     <li class ="col-md">
      <%= link_to 'Agregar Aula', new_aula_path %>
     </li>
    </ul>
  </nav>
</header>

<body>
<%= form_with(model: curso, local: true) do |form| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div id="wrapper">
        <form action="" method="post">
            <fieldset>
                <legend>NUEVO CURSO</legend>
                <div class="field">
                <%= form.label :nombre %>
                <%= form.text_field :nombre %>
              </div>

              <div class="field">
                <%= form.label :carrera %>
                <%= form.select(:carrera, Curso::CLASS_LIST_CARRERA) %>
              </div>

              <div class="field">
                <%= form.label :cantidadalumnos %>
                <%= form.number_field :cantidadalumnos %>
              </div>

              <div class="field">
                <%= form.label :turno %>
                <%= form.select(:turno, Curso::CLASS_LIST_TURNO) %>
              </div>

              <div class="field">
                <%= form.label :comision %>
                <%= form.select(:comision, Curso::CLASS_LIST_COMISION) %>
              </div>

              <div class="field">
                <%= form.label :asignado %>
                <%= form.check_box :asignado %>
              </div>

              <div class="actions">
                   <%= form.submit %>  
              </div>
            <% end %>
            </fieldset>    
        </form>
    </div>
</body>



  

app/views/cursos/edit.html.erb
<h1>Editar Curso</h1>

<%= render 'form', curso: @curso %>
<div align="center">
<%= link_to 'Ver', @curso %> |
<%= link_to 'Volver', cursos_path %>
</div>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Cursos</h1>

<header>
  <nav class="be-red white">
    <ul class = "no-list row center-xs">
      <li class ="col-md">
      <%= link_to 'Agregar Curso', new_curso_path %>
     </li>
     <li class ="col-md">
      <%= link_to 'Agregar Aula', new_aula_path %>
     </li>
    </ul>
  </nav>
</header>

<body>
<div id="main-container"> 
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Carrera</th>
      <th>Cantidad Alumnos</th>
      <th>Turno</th>
      <th>Comision</th>
      <th>Asignado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nombre %></td>
        <td><%= curso.carrera %></td>
        <td><%= curso.cantidadalumnos %></td>
        <td><%= curso.turno %></td>
        <td><%= curso.comision %></td>
        <td><%= curso.asignado %></td>
        <td><%= link_to 'Ver', curso %></td>
        <td><%= link_to 'Editar', edit_curso_path(curso) %></td>
        <td><%= link_to 'Borrar', curso, method: :delete, data: { confirm: 'Esta ud. seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

</body>

app/views/cursos/new.html.erb
<br>
<br>
<%= render 'form', curso: @curso %>
<!-- <div align="center">
<%= link_to 'Volver al listado de cursos', cursos_path %>
</div> -->

app/views/cursos/show.html.erb
<div id="wrapper">
  <fieldset>
    <p id="notice"><%= notice %></p>
      <legend>Curso Generado</legend>
      <div>
      <p>
        <strong>Nombre:</strong>
        <%= @curso.nombre %>
     </p>
    </div>
    <div>
      <p>
      <strong>Carrera:</strong>
      <%= @curso.carrera %>
      </p>
    </div>
    <div>
      <p>
      <strong>Carrera:</strong>
      <%= @curso.carrera %>
      </p>
    </div>
    <div>
    <p>
      <strong>Cantidadalumnos:</strong>
      <%= @curso.cantidadalumnos %>
    </p>
  </fieldset>    
</div>


	<p>
  <strong>Turno:</strong>
  <%= @curso.turno %>
</p>

<p>
  <strong>Comision:</strong>
  <%= @curso.comision %>
</p>

<p>
  <strong>Asignado:</strong>
  <%= @curso.asignado %>
</p>

<div class="btn">
<%= link_to 'Editar', edit_curso_path(@curso) %> |
<%= link_to 'Volver', cursos_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TPRubyonrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>